services:
  - type: web
    name: websocket-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000